language: node_js

node_js:
  - node

script: 
  - npm run build
  - npm test

install:
  - npm i -g npm@latest
  - npm install

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules
