language: node_js

node_js:
  - 6
  - 5
  - 4

script: npm run build

install:
  - npm i -g npm@latest
  - npm install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
