language: node_js
node_js:
- node
script:
- npm run build
- npm test
install:
- npm i -g npm@latest
- npm install
notifications:
  email:
    on_failure: change
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_60360203af42_key -iv $encrypted_60360203af42_iv
  -in wetracker-60407b8e08ac.json.enc -out wetracker-60407b8e08ac.json -d
deploy:
  provider: gae
  keyfile: wetracker-60407b8e08ac.json
  project: wetracker-159510
