language: node_js

node_js:
  - 6
  - 5
  - 4

script: npm run build

install:
  - npm i -g npm@latest
  - npm install

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules
