# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WeTracker 
description: > # this means to ignore newlines until "baseurl:"
  A Collaborative, Online Music Creation Suite
repository: pgregory/wetracker
baseurl:   # the subpath of your site, e.g. /blog
url: https://wetracker.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: pgregory 
email: aqsis1@gmail.com

navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog
  - text: Docs
    url: /documentation/intro

social:
  - service: github
    username: pgregory
    link: https://github.com/pgregory
  - service: twitter
    username: pcgregory
    link: https://twitter.com/pcgregory

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  documentation:
    output: true
